config/routes.rb
Weafam::Application.routes.draw do


  resources :similars_founds, except: [:update, :show, :edit]

  resources :relations

  resources :updates_events

  resources :updates_feeds, except: [:update, :show, :destroy, :new, :edit]

  resources :weafam_settings

  resources :connection_requests
  # connection_requests_controller
  match 'show_user_requests' => 'connection_requests#show_user_requests', via: :get
  match 'show_user_requests' => 'connection_requests#show_user_requests', via: :post

  match 'show_one_request' => 'connection_requests#show_one_request', via: :get
  match 'show_one_request' => 'connection_requests#show_one_request', via: :post

  match 'yes_connect' => 'connection_requests#yes_connect', via: :get
  match 'yes_connect' => 'connection_requests#yes_connect', via: :post

  match 'no_connect' => 'connection_requests#no_connect', via: :get
  match 'no_connect' => 'connection_requests#no_connect', via: :post

  match 'make_connection_request' => 'connection_requests#make_connection_request', via: :get
  match 'make_connection_request' => 'connection_requests#make_connection_request', via: :post


  # search similars & connecting
  # SearchSimilars controller
  match 'internal_similars_search' => 'similars#internal_similars_search', via: :get
  match 'show_similars_data' => 'similars#show_similars_data', via: :get
  match 'show_similars_data' => 'similars#show_similars_data', via: :post
  get 'similars/index'
  match 'connect_similars' => 'similars#connect_similars', via: :get
  match 'keep_disconnected_similars' => 'similars#keep_disconnected_similars', via: :get
  match 'connect_similars' => 'similars#connect_similars', via: :post
  match 'keep_disconnected_similars' => 'similars#keep_disconnected_similars', via: :post
  match 'disconnect_similars' => 'similars#disconnect_similars', via: :get
  match 'disconnect_similars' => 'similars#disconnect_similars', via: :post
  match 'check_connected_similars' => 'similars#check_connected_similars', via: :get
  match 'check_connected_similars' => 'similars#check_connected_similars', via: :post

  # CommonLog controller
  resources :common_logs, except: [:update, :edit, :show]

  get 'common_logs/index'
  # match 'connect_similars' => 'similars_founds#connect_similars', via: :get
  get 'common_logs/create'
  # get 'common_logs/show'
  get 'common_logs/destroy'
  match 'rollback_logs' => 'common_logs#rollback_logs', via: :post
  match 'rollback_logs' => 'common_logs#rollback_logs', via: :get
  match 'mark_rollback' => 'common_logs#mark_rollback', via: :post
  match 'mark_rollback' => 'common_logs#mark_rollback', via: :get


  # messages controller
  resources :messages, except: [:update, :show, :destroy, :edit]

  match 'send_message' => 'messages#send_message', via: :get
  match 'send_message' => 'messages#send_message', via: :post

  match 'enter_new_message' => 'messages#enter_new_message', via: :get
  match 'enter_new_message' => 'messages#enter_new_message', via: :post

  match 'write_new_message' => 'messages#new_message', via: :get, as: :write_new_message
  match 'write_new_message' => 'messages#new_message', via: :post, as: :send_new_message

  match 'show_all_messages' => 'messages#show_all_messages', via: :get
  match 'show_all_messages' => 'messages#show_all_messages', via: :post

  match 'show_all_dialoges' => 'messages#show_all_dialoges', via: :get
  #match 'show_all_dialoges' => 'messages#show_all_dialoges', via: :post

  match 'show_one_dialoge' => 'messages#show_one_dialoge', via: :get
  #match 'show_one_dialoge' => 'messages#show_one_dialoge', via: :post

  match 'mark_important' => 'messages#mark_important', via: :post
  #match 'important_message' => 'messages#important_message', via: :post

  match 'delete_message' => 'messages#delete_message', via: :post
  #match 'delete_message' => 'messages#delete_message', via: :post

  match 'delete_one_dialogue' => 'messages#delete_one_dialogue', via: :post

  match 'spam_dialoge' => 'messages#spam_dialoge', via: :get


  # pages controller
  match 'landing' => 'pages#landing', via: :get
  match 'news' => 'pages#news', via: :get
  match 'mail' => 'pages#mail', via: :get
  match 'mypage' => 'pages#mypage', via: :get
  match 'search' => 'pages#search', via: :get
  match 'conversation' => 'pages#conversation', via: :get
  match 'start_enter' => 'pages#start_enter', via: :get
  match 'start_dialoge' => 'pages#start_dialoge', via: :get # запуск процесса диалогового ввода стартового древа

  #todo: убрать путаницу в названиях методов main и start
  # main controller
  match 'main_page' => 'main#main_page', via: [:get, :post]
  match 'search_tree_match' => 'main#search_tree_match', via: :get
  match 'relative_menu' =>   'main#relative_menu', via: :get
  match 'match_approval' => 'main#match_approval', via: :get
  match 'add_new_profile' => 'new_profile#add_new_profile', via: [:get, :post]


  # new_profile controller
  match 'make_new_profile' => 'new_profile#make_new_profile', via: :get
  match 'make_tree_row' => 'new_profile#make_tree_row', via: :get
  match 'make_profilekeys_rows' => 'new_profile#make_profilekeys_rows', via: :get
  match 'add_new_profile' => 'new_profile#add_new_profile', via: :get
  match 'add_new_profile' => 'new_profile#add_new_profile', via: :post


  # connect_users_trees controller
  match 'connection_of_trees' => 'connect_users_trees#connection_of_trees', via: :get
  match 'get_trees_to_connect' => 'connect_users_trees#get_trees_to_connect', via: :get
  match 'connect_users' => 'connect_users_trees#connect_users', via: :get
  match 'connect_profiles' => 'connect_users_trees#connect_profiles', via: :get
  match 'connect_trees' => 'connect_users_trees#connect_trees', via: :get
  match 'connect_profiles_keys' => 'connect_users_trees#connect_profiles_keys', via: :get

  get "connect_users_trees/connect_users"
  get "connect_users_trees/connect_profiles"
  get "connect_users_trees/connect_trees"
  get "connect_users_trees/connect_profiles_keys"


  get 'profile/context-menu', to: 'profiles#context_menu', as: :profile_context_menu

  resources :profiles, except: [:index, :edit] do
    get '/edit/data', to: 'profiles#edit', as: :edit_data
    get '/version/:profile_data_id', to: 'profiles#show', as: :profile_data_version
  end
  match 'rename_profile' => 'profiles#rename_profile', via: :get



  match '/profiles/avatar', to: 'avatar#upload', as: :upload_avatar, via: [:get, :post]

  get '/crop/avatar/:profile_id', to: 'profiles#crop', as: :crop_avatar


  # Profile Data
  ##################################################
  resources :profile_datas, only: [:update, :create]


  match '/passwrod/reset' => 'password#reset', via: [:get, :post], as: :reset_password


  # for Mailer
  match 'enter_email' => 'profiles#enter_email', via: :get
  match 'enter_email' => 'profiles#enter_email', via: :post

  match 'invitation_email' => 'weafam_mailer#invitation_email', via: :get
  match 'invitation_email' => 'weafam_mailer#invitation_email', via: :post


  # Send invite email
  resources :invites, only: [:new, :create]


  # Debug path - Login as user
  get 'login_as_user/:user_id',             to: 'welcome#login_as_user',       as: :login_as_user


  # Users Sessions Signup
  ##################################################
  resources :users


  resources :sessions, except: :edit
  get  'login',      to:   "sessions#new",      as: :login
  get  'logout',     to:   "sessions#destroy",  as: :logout
  get  'signup',     to:   'signup#index',      as: :signup
  post 'register',   to:   'signup#create',     as: :register
  get  'pending',    to:   'signup#pending',   as: :pending




  # Home
  ##################################################
  get '/home',        to: 'home#index',  as: :home
  get '/home/search', to: 'home#search', as: :home_search

  match 'show_similars' => 'home#show_similars', via: :post

  # Autocompletes
  ##################################################
  get '/autocomplete/names', to: 'autocomplete#names'


  # Names
  ##################################################
  # resources :names
  get '/names/find', to: "names#find", as: :find_name
  # add new name (from user)
  resources :names, only: [:new, :create]



  # API
  ##################################################
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get 'circles', to: 'circles#show'
      get 'search',  to: 'search#index'
      get 'search/iternal',  to: 'search#iternal'
    end
  end


  # Meteor
  ##################################################
  namespace :meteor, defaults: {format: 'json'} do
    namespace :v1 do

      get :login, to: 'login#login'

      namespace :validations do
        namespace :emails do
          get :exist, to: "emails#exist"
        end
      end


      namespace :signup do
        post :create, to: 'signup#create'
      end


      namespace :passwords do
        get :reset, to: 'passwords_reset#reset'
      end


      namespace :profiles do
        get :destroy, to: "profiles_destroy#destroy"
        get :create,  to: "profiles_create#create"
        get :rename,  to: "profiles_rename#rename"
      end


      namespace :names do
        get :create,  to: "names_create#create"
      end

      namespace :common_logs do
        get :rollback, to: "rollbacks#rollback"
      end

      namespace :connection_requests do
        get :no_connect, to: "no_connect#no_connect"
        get :yes_connect, to: "yes_connect#yes_connect"
        get :make_request, to: "make_request#make_request"
      end

      namespace :similars_founds do
        get :search_similars, to: "similars_founds#search_similars"
      end

      namespace :similars_connection do
        get :connecting_similars, to: "similars_connection#connecting_similars"
      end

      namespace :profile_datas do
        get :update, to: "profile_datas_update#update"
        post :add_photo, to: "profile_datas_photos#add"

app/controllers/common_logs_controller.rb
class CommonLogsController < ApplicationController
  include CommonLogsHelper

  layout 'application.new'

  before_filter :logged_in?

  # @note Show All types of Common_logs for connected_users
  def index
    # get & show tree data
    tree_info = Tree.get_tree_info(current_user)

    # to show similars connected in view & for RSpec
    @tree_info = tree_info
    @connected_users = tree_info[:connected_users]
    @current_user_id = current_user.id
    view_tree_data(tree_info) unless tree_info.empty?  # to index.html.haml

    # get one tree all types common_logs
    # tree_all_logs = CommonLog.get_tree_all_logs(current_user)
    tree_all_logs = CommonLog.get_tree_all_logs(tree_info[:connected_users])

    # show connected tree all types common_logs
    view_common_logs(tree_all_logs) unless tree_all_logs.empty?  # to index.html.haml
  end


  # @note Пометка Common_log - граница отката дерева
  # @param params[:common_log_id]  ID помеченного Common_log - из view
  def mark_rollback
    unless params[:common_log_id].blank?
      @common_log_id = params[:common_log_id].to_i
      @common_log_type = CommonLog.find(params[:common_log_id].to_i).log_type
      @common_log_date = CommonLog.find(params[:common_log_id].to_i).created_at#.strftime("%F")
      @log_date_to_show = @common_log_date.strftime("%F")
    end
    respond_to do |format|
      format.html
      format.js { render 'common_logs/mark_rollback' }
    end
  end


  # @note Возврат дерева - откат на выбранную дату
  # @param params[:rollback_date]
  # @param current_user
  def rollback_logs
    rollback_id   = params[:rollback_id]
    CommonLog.rollback(rollback_id, current_user)
  end


end

app/controllers/meteor/v1/common_logs/rollbacks_controller.rb
module Meteor
  module V1
    module CommonLogs
      class RollbacksController < MeteorController

        before_filter :authenticate

        def rollback
          # roll = { status: true }
          rollback_id = params[:id]
          logger.info "In RollbacksController: rollback_id = #{rollback_id}"
          logger.info "In RollbacksController: @current_user.id = #{@current_user.id}  "
          logger.info "In RollbacksController: current_user.id = #{current_user.id}  "
          CommonLog.rollback(rollback_id, @current_user)
          # respond_with roll
          logger.info "In RollbacksController: After rollback: @error = #{@error}  " if @error
          logger.info "In RollbacksController: After rollback"

          if @error
            respond_with @error
          else
            respond_with(status:200)
          end
        end



        end
      end
   end
end

app/helpers/common_logs_helper.rb
module CommonLogsHelper

  # Отобр-е параметров дерева и sim_data во вьюхе
  def view_tree_data(tree_info)
    @tree_info = tree_info
    @current_user_id = current_user.id
    # @paged_similars_data = pages_of(@similars_founds, 10) # Пагинация ТОЛЬКО ДЛЯ МАССИВА ХЭШЕЙ - по 10 строк на стр.
  end

  # Отобр-е истории дерева - логов его развития - во вьюхе
  def view_common_logs(tree_all_logs)
    @current_user_id = current_user.id
 #   @paged_common_logs_data = pages_of(common_logs_data, 10) # Пагинация - по 10 строк на стр.
 #    logger.info "In view_common_logs_data: tree_all_logs = #{tree_all_logs} "
    @tree_all_logs = tree_all_logs
  end



end

app/views/common_logs/_rollback.html.haml
%br
%h1 Вернуть назад историю дерева к выбранной дате: #{@log_date_to_show}? (Ваше решение)
= link_to 'Да, вернуть дерево в состояние на выбранную дату', rollback_logs_path(rollback_id: @common_log_id, rollback_date: @common_log_date), method: :post, remote: true, class: [:bttn, :red]
= link_to 'Нет - к просмотру дерева', home_path, class: [:bttn, :green]
%br
%br
%br

app/views/common_logs/index.html.haml
.container#common_log
  -#%h1 Просмотр общих логов дерева
  -#%br

  -#%h1 Данные о текущем дереве
  -#- if @tree_info.empty?
  -#  %table
  -#    %tr
  -#      %td.left.grey.italic
  -#        Данныx о текущем дереве - нет
  -#- else
  -#  %h2 На сайте - пользователь (current_user.id): #{@current_user_id}
  -#  %h2 Пользователи - авторы дерева: #{@tree_info[:connected_users]}
  -#  -#%h2 ID Профилей Пользователей - авторов дерева: #{@tree_info[:users_profiles_ids]}
  -#  -#%h2 Массив профилей в дереве:     #{@tree_info[:tree_is_profiles]}
  -#  -#%h2 Количество профилей в дереве: #{@tree_info[:tree_profiles_amount]}
  -#  %h2 Полный массив профилей в дереве (с авторами):  #{@tree_info[:all_tree_profiles]}
  -#  %h2 Полное количество профилей в дереве (с авторами): #{@tree_info[:all_tree_profiles_amount]}
  -#%br
  -#

  -#- if @paged_common_logs_data.blank?
  - if @tree_all_logs.blank?
    %table
      %tr
        %td.left.grey.italic
          %h2 У дерева пока еще нет истории...
          %br
          = link_to 'К просмотру дерева', home_path, class: [:bttn, :green]

  - else
    %h1 История развития твоего дерева
    %br
    %table
      %tr
        %th Лог ID
        %th Дата *
        %th Дерево
        %th Действие
        %th Имя
        %th Профиль *
        %th Номер лога *
        -#%th
        %th
      -#- @paged_common_logs_data.each do |common_logs_data|
      - @tree_all_logs.each do |tree_one_log|
        -#%tr{data: {common_log_id: tree_one_log.id}}
        %tr
          -#%td.rollback= common_logs_data.id
          %td= tree_one_log.id
          %td= tree_one_log.created_at
          %td= tree_one_log.tree_user_name
          %td= LogType.name_log_type(tree_one_log.log_type)  #
          %td= tree_one_log.agent_name #
          %td= tree_one_log.profile_id #
          %td= tree_one_log.log_id

          %td= link_to 'Выбрать', mark_rollback_path(common_log_id: tree_one_log.id), method: :post, remote: true,  id: 'name_container', class: :messages

  .point
    %h1
    %h2
  .log_id
    %h2


  .after_rollback

  %br


    -#%input type="button" name="OK" class="ok" value="OK"
    -#%h1 Вернуть назад историю дерева к выбранной дате? (Ваше решение)
    -#= link_to 'Да, вернуть дерево в состояние на выбранную дату', rollback_add_logs_path(rollback_date: '2015-03-14 10:54:05 UTC'), method: :post, remote: true, class: [:bttn, :red]
    -#= link_to 'Нет - к просмотру дерева', home_path, class: [:bttn, :green]

    -#= paginate @paged_common_logs_data
    -#%h2 Выбранный ряд: #{@common_log_id_selected.inspect}

  %br
  %br

app/views/common_logs/mark_rollback.js.erb
var commonLogId = "<%= params[:common_log_id].to_i %>";
console.log(commonLogId);
var commonLogType = ' <%= @common_log_type %> ';
console.log(" commonLogType = " + commonLogType );
var commonLogDate = ' <%= @log_date_to_show %> ';
console.log(" commonLogDate = " + commonLogDate );


var textStrin = "Выбран лог: " + commonLogId  + "; На дату: " + commonLogDate + "; Тип лога: " + commonLogType + ';<br>';
console.log("In mark_rollback.js: params[:common_log_id] = " + "<%= params[:common_log_id].to_i.inspect %>" + textStrin);

$('.point h2').before().empty().append(textStrin);

$('.log_id').after().html("<%= j render 'common_logs/rollback' -%>");

app/views/common_logs/rollback_add_logs.js.erb
var rollbackId = "<%= params[:rollback_id] %>";
var rollbackDate = "<%= params[:rollback_date] %>";
console.log('rollbackId = ' + rollbackId);
console.log('rollbackDate = ' + rollbackDate);
if(typeof rollbackDate != "undefined" && rollbackDate != null && rollbackDate.length > 0){
    console.log("After RollBack Add Logs - chosen");
    var textStr = '<br>' + 'Возврат дерева в состояние на выбранную дату = ' + rollbackDate + ' - совершен!'
            + '<br>' + '<br>';
    $('.log_id').empty();
    //$('.point h2').empty();
    $('.point h2').empty().before().append(textStr).fadeOut(3000);
    setTimeout("window.location.href='<%= home_path %>';",2000);


}



$("#table tr").click(function(){
//$(".rollback").click(function(){
    console.log('In function');

    $(this).addClass('selected').siblings().removeClass('selected');
    var value=$(this).find('td:first').html();
    alert(value);
    console.log('value = ' + value);

});

$('.ok').on('click', function(e){
    alert($("#table tr.selected td:first").html());
});

app/views/common_logs/rollback_logs.js.erb
var rollbackId = "<%= params[:rollback_id] %>";
var rollbackDate = "<%= params[:rollback_date] %>";
if(typeof rollbackDate != "undefined" && rollbackDate != null && rollbackDate.length > 0){
    var textStr = '<br>' + 'Return tree to chosen date state = ' + rollbackDate + ' - completed!' + '<br>';
    $('.log_id').empty();
    $('.point h2').empty().before().append(textStr).fadeOut(3000);
    setTimeout("window.location.href='<%= home_path %>';",2000);
}

$("#table tr").click(function(){
    $(this).addClass('selected').siblings().removeClass('selected');
    var value=$(this).find('td:first').html();
    alert(value);
});

$('.ok').on('click', function(e){
    alert($("#table tr.selected td:first").html());
});